### ISSUE TITLE
ヒヤリハットのPDFを「データ化」(JSON化)する

### ISSUE THREAD

**Issue by masum** [Shizuoka-Oden/kuro-hanpen#10]

**Comment by Nyakano** [comment]
とりあえず、手動でがんばる
なかのパーサー

**Comment by masum** [comment]
検索できるように、緯度経度の情報もお願いします

**Comment by Nyakano** [comment]
[ヒヤリハットマップ](http://dataset.city.shizuoka.jp/dataset/hiyarihatto)
から取れそうなデータ。

```json
{
  id: "連番(1,2,3・・・)"
  address: "住所を町名ぐらい（安東2丁目）",
  lank: "危険度(A,B,C)",
  description: "説明(歩道が狭いよ。気をつけて！)",
  map:  {
    longitude: "緯度(42.6803689)",
    latitude: "経度(141.5844374)"
       }
}
```
住所、緯度経度は手動でやるしかなさそう。

**Comment by Nyakano** [comment]
こんな感じで作成する。
```
[
    {
        "type": "ヒヤリハット",
        "preset": true,
        "title": "急な飛び出しヒヤリ・ハット",
        "address": "駿河区中田１丁目７−２０",
        "description": "飛び出し多発！",
        "location": {
            "lat": 34.96433678315455,
            "lon": 138.3928146958351
        }
    }
]
```

データが多いので分割する

**Comment by Nyakano** [comment]
コミットの単位分けたいので、分割した。
[静岡市駿河区あんしん歩行エリアからヒヤリハットのデータ抽出 #96](https://github.com/Shizuoka-Oden/kuro-hanpen/issues/96)
[静岡市葵区あんしん歩行エリアからヒヤリハットのデータ抽出 #97](https://github.com/Shizuoka-Oden/kuro-hanpen/issues/97)
[静岡市清水地区あんしん歩行エリアからヒヤリハットのデータ抽出 #98](https://github.com/Shizuoka-Oden/kuro-hanpen/issues/98)
