### ISSUE TITLE
gulpにてElasticSearchのデータ登録/更新実装

### ISSUE THREAD

**Issue by masum** [Shizuoka-Oden/kuro-hanpen#15]

**Comment by mid0111** [comment]
？？
なんでgulpなんでしょう？？？
素のnodeとかよりおいしいのかな。

**Comment by masum** [comment]
自分の願望で書いちゃった
なんでもいいとおもいます。
個人的には素のnode乱立するよりは整理されてオイシイと思うのですが、やりやすい感じでいいと思うス

**Comment by mid0111** [comment]
Geo 検索用のマッピング定義とか検索方法とか
https://shizuoka-oden.esa.io/posts/187

**Comment by mid0111** [comment]
これってkuro-hanpen プロジェクトのgulp task でいいのかな？
データ用に別プロジェクト起こしたほうがいいかな？

kuro-hanpen プロジェクトに入れる場合こんな感じにするのかな？

```bash
.
├── README.md
├── data # ここにJSONデータ入れる
│   ├── fuga.json
│   └── hoge.json
├── package.json
├── protractor.conf.js
└── src
```

dataディレクトリ配下のJSONのフォーマット例
```json:fuga.json
[
  {
    "fuga": "fuga1",
    "piyo": "piyo1"
  }, {
    "fuga": "fuga2",
    "piyo": "piyo2"
  }
]
```

**Comment by mid0111** [comment]
#30
