### ISSUE TITLE
かっこいいドメイン考える。安ければ契約する

### ISSUE THREAD

**Issue by masum** [Shizuoka-Oden/kuro-hanpen#18]
shizuokao.den みたいな感じがいい

**Comment by Nyakano** [comment]
テーマも具体的に書きたいっす。
ふと目にはいったやつ。それをドメインてきな。
[検索より探索 fun to Tokyo](http://www.flatcord.co.jp/blog/marketing/jre.html)
[検索より探索画像](https://www.facebook.com/funtokyo.jreast/posts/908328005908887)

**Comment by kut-arika** [comment]
AWS Route53で取れるドメインで一桁ドルのドメイン。
.co.uk - $9.00
.de - $9.00
.be - $9.00
.me.uk - $8.00
.org.uk - $9.00

**Comment by kut-arika** [comment]
１０ドル代
.com - $12.00
.net - $10.00
.org - $12.00
.com.au - $15.00
.info - $12.00
.ca - $13.00
.me - $17.00
.us - $15.00
.eu - $13.00
.agency - $19.00
.biz - $12.00
.blue - $15.00
.ch - $12.00
.club - $12.00
.co.za - $13.00
.es - $10.00
.exposed - $19.00
.fr - $12.00
.futbol - $12.00
.in - $15.00
.it - $15.00
.kim - $15.00
.link - $10.00
.mobi - $12.00
.net.au - $15.00
.ninja - $18.00
.nl - $10.00
.onl - $15.00
.pink - $15.00
.qpon - $15.00
.red - $15.00
.shiksha - $16.00

**Comment by kut-arika** [comment]
http://www.onamae.com/campaign/16th/726?banner_id=726_16th_com_50_a&waad=mXng7oZ7&utm_source=google&utm_medium=paidsearch
今ならxyzドメインが50円

**Comment by kut-arika** [comment]
無料ならばtkドメインかなぁ
http://www.dot.tk/ja/index.html?lang=ja

**Comment by kut-arika** [comment]
とりあえず sz-oden.tk でとる。
https://blog.apar.jp/cloud/2142/

**Comment by kut-arika** [comment]
sz-oden.tk とりました。
和田さんAWSのRoute53に設定しています。
やり方は上のコメントの方法です。
