### ISSUE TITLE
esa.ioにかわるwiki(markdown)サービスを調査

### ISSUE THREAD

**Issue by masum** [Shizuoka-Oden/kuro-hanpen#2]
esa.ioは12月いっぱいで試行期限がきれるので、現在の記事を移行方法を含めて、新しいサービスを探す

**Comment by kut-arika** [comment]
http://qiita.com/mizoki/items/a5b8fd7288b096c2b47a
https://y-knot.jp/categories/document-sharing
http://web-d.navigater.info/cat3/teamshare6.html

**Comment by kut-arika** [comment]
wri.pe
https://wri.pe/


stackedit
https://stackedit.io/


circleaf
http://www.circleaf.com/


lodge
https://github.com/lodge/lodge


storyboards
http://www.storyboards.jp/


docbase
https://docbase.io/


Inc
https://sendtoinc.com/


Honey
https://honey.is/


svgn
https://svgn.biz/

**Comment by watagashi** [comment]
[Gist](https://gist.github.com/) で secret gist を作るという方法もありますね。
チームだと使いにくいけれど。

**Comment by KazuhikoKuroda** [comment]
[Evernote](https://evernote.com/intl/jp/)に共有垢作って[Marxico](http://nelog.jp/marxico)使うってのもいいかも。
タグでフォルダ代替とか。

**Comment by masum** [comment]
どれもイマイチなので、esa.io 再作成するのでもいいような気がしてきた
esa.ioにExportはあるけど、importがないなーって思っていたら、APIで出来そうです。
https://docs.esa.io/posts/102

**Comment by kut-arika** [comment]
移行スクリプトは書いてみました。
全員が新しい方に登録完了次第、移行したいと思います。

**Comment by kut-arika** [comment]
#24 残り作業はこっちでやるとして、クローズします。
