### ISSUE TITLE
JAWSフレームワークが今回の開発で使えそうか調査する

### ISSUE THREAD

**Issue by masum** [Shizuoka-Oden/kuro-hanpen#23]
https://github.com/jaws-framework/JAWS

**Comment by kut-arika** [comment]
名前が変わってserverlessになってました。
調べてみた結果をまとめました。
感覚としては結構いい感じ。
まだドキュメントが少ないが、やってみる価値はあると思います。

**Comment by kut-arika** [comment]
serverless使います！！！
