### ISSUE TITLE
アプリ基本設計

### ISSUE THREAD

**Issue by Nyakano** [Shizuoka-Oden/kuro-hanpen#25]
通学経路や、よく行く遊び場までの経路付近に危険（ヒヤリハット）箇所がないか表示するアプリの設計を考える。
  
まずはesaにかく。

**Comment by Nyakano** [comment]
https://shizuoka-oden.esa.io/posts/181

**Comment by Nyakano** [comment]
たたき台として書いてみました。

**Comment by kut-arika** [comment]
黒田さんに続き考えてもらい中。
