### ISSUE TITLE
スケジュール共有サービスを調べる

### ISSUE THREAD

**Issue by Nyakano** [Shizuoka-Oden/kuro-hanpen#28]
皆様が集まれる日を共有するためのサービスを調査。
* 飲み会の出欠確認するみたいなやつ

**Comment by watagashi** [comment]
-   [伝助 スケジュール調整サービス](http://densuke.biz/)
-   [調整さん - 簡単スケジュール調整、出欠管理ツール](https://chouseisan.com/)

定番なので知ってるかもだけれど。

-   [TimeTree【タイムツリー】 - グループでのスケジュール共有とプライベートの予定管理ができるカレンダーアプリ](http://timetreeapp.com/ja/)

よく聞くけれどまだ使ったことない。

**Comment by kut-arika** [comment]
調整さんで作った！
リンクはesaのトップページに！
