### ISSUE TITLE
事務所以外で打ち合わせや開発の出来る場所がないか調べる

### ISSUE THREAD

**Issue by watagashi** [Shizuoka-Oden/kuro-hanpen#29]
各自の事務所のような制約が少なくて集まりやすい場所を調べる。

-   レンタルオフィス
-   ネットカフェ
-   カラオケやパーティールーム?
-   公共施設
-   ほか

**Comment by watagashi** [comment]
生涯学習施設利用者登録票を提出してみた。
審査から利用できるようになるまで1週間ちょっと掛かるとのこと。

**Comment by masum** [comment]
２３時まで利用できるのが魅力的
http://kaigishitsu-shizuoka.com/yoyaku/room_B414.html
9:00〜23:00 で2万円

18:30-23:00 で8200円

**Comment by KazuhikoKuroda** [comment]
パルシェの会議室
人数にもよるけど最安で 18:00-21:00 3,600円
http://kaigi.parche.co.jp/Default.asp

近い。

**Comment by kut-arika** [comment]
大塚家は提供できます。
どっちかが仕事終わっていれば平日夜でもOKっす

**Comment by watagashi** [comment]
ネタが出尽くしたようなのと生涯学習施設利用者登録が通ったのと大塚家で実績が出来た (行けなかったけれど有り難うございます) ということでクローズしちゃいます。
