### ISSUE TITLE
アプリエントリー資料作成

### ISSUE THREAD

**Issue by kut-arika** [Shizuoka-Oden/kuro-hanpen#48]

**Comment by watagashi** [comment]
雛形 [[WIP] プロジェクト/アプリ登録 - shizoka-oden.esa.io](https://shizoka-oden.esa.io/posts/156) 作ってみました。

これをみんなで書いていけば良い?

**Comment by watagashi** [comment]
エントリーしたのでこれはクローズですね。

-   [ヒヤロコシェア - シズオカアプリコンテスト応募作品 #39](https://shizuoka-app-awards.jp/apps/39)
