### ISSUE TITLE
アプリ名を決めよう

### ISSUE THREAD

**Issue by KazuhikoKuroda** [Shizuoka-Oden/kuro-hanpen#58]
そろそろ決めよう。
呼称がないと不便だし、アイコンも作りにくいし。
[基本セッケー](https://shizuoka-oden.esa.io/posts/181)

候補名をここにコメントしてほしい。

**Comment by KazuhikoKuroda** [comment]
「OzoiShare」
おぞい（品質が悪いとか）

「CholayShare」
ちょれー（ちょろい・弱い）

あえてマップとか使わないで方言を横文字にしたこのセンスどうよ。

**Comment by kut-arika** [comment]
ここしょんねーら
みんなでつくるヒヤリまっぷ
ヒヤロコシェア

**Comment by KazuhikoKuroda** [comment]
調整さんにアンケート作った。
まだ募集中だけど、とりあえず明後日の朝まで投票受付中にすっかな。
https://chouseisan.com/s?h=b7a8f33d19a24912964869534f9d302a

**Comment by KazuhikoKuroda** [comment]
:clap::clap::clap:「ヒヤコロシェア」に決定！！  :clap::clap::clap:
