### ISSUE TITLE
静岡オープンデータの公園、橋等、住所を持つデータを洗い直す

### ISSUE THREAD

**Issue by masum** [Shizuoka-Oden/kuro-hanpen#7]

**Comment by mid0111** [comment]
イタリーまでにちょっとは役にたちたくちょこっとやってみました。
リンクはって大丈夫かわかんないので slack で。

シズオカポータルのページで名前昇順で６ページ目↓まで見た。
http://dataset.city.shizuoka.jp/dataset?q=&sort=title_string+asc&page=6

やり方は
* 位置情報ありそうなもの抜き出す。
* あんまり重たかったりタイトル的に関係なさすぎるものは排除。

明日からたぶんしばらくネット見れないので、これ続けるなり、別の方法なりでいい感じのデータ見つけてくれる方大募集中です。
よろしくです。

**Comment by mid0111** [comment]
esa にリンク貼りました。
とりあえずデータはひととおりさらった。
https://shizuoka-oden.esa.io/posts/188

長いこと打ち合わせ出れてないので、議事録は読んでるけど、アプリの内容いまいちわかってないです。
なので、**「このデータ使えそう」みたいのマークつけてもらえると嬉しい。**

**Comment by mid0111** [comment]
- [x] アプリに関係ありそうで位置情報持つデータ洗い出す
- [ ] アプリに使いたいデータ洗い出す（←ほしいやつあったらエクセルに記入してね）

**Comment by mid0111** [comment]
コメントなさげなので issue の方はとじちゃいます。
