### ISSUE TITLE
生成したJSONデータをElasticSearchに登録して検索できるようにする

### ISSUE THREAD

**Issue by masum** [Shizuoka-Oden/kuro-hanpen#9]

**Comment by mid0111** [comment]
- [ ] 市立小学校、中学校及び高等学校一覧
  - [ ] 小学校
  - [ ] 中学校
  - [ ]  高校
- [ ] 葵区・駿河区内にある公園基本情報一覧表

**Comment by mid0111** [comment]
間違ってこっちでやっちゃった。
close #8
